name: Prompt Evaluation

on:
  pull_request:
    paths:
      - 'prompt/**' # Trigger the action when files in the 'prompts' directory are modified

jobs:
  evaluate:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write # Required to post comments on Pull Requests

    steps:
      - uses: actions/checkout@v4
      - uses: promptfoo/promptfoo-action@v1
        #with:
          # Optional: Specify the path to your promptfoo config file
          # config: '../promptfoo.yaml'
